"""gRPC proto files package.

This package contains the generated gRPC code from tool_service.proto.
The proto files are generated by running:
  python -m strix.runtime.remote_tool_server.generate_proto
"""

# These will be available after proto generation
try:
    from . import tool_service_pb2
    from . import tool_service_pb2_grpc

    __all__ = ["tool_service_pb2", "tool_service_pb2_grpc"]
except ImportError:
    # Proto files not generated yet
    __all__ = []
